### PR TITLE
Completes UDRA changes as part of REPPBFORM 619

### PR DESCRIPTION
**Pull request by BAucoinHC**

### CODE REVIEW

**Review by AMckayHC — CHANGES_REQUESTED** [review]
Can you remove the .idea and build folder from the commit?

**Comment by BAucoinHC** [comment]
I have added a commit to remove the build and .idea folders

**Comment by BAucoinHC** [comment]
> Can you remove the .idea and build folder from the commit?

I have added a commit to the pr that removes those folders

**Review by AMckayHC — CHANGES_REQUESTED** [review]
Can you also remove dev/src/forms_R1/node_modules folder?  Thanks!

**Pull request closed without merging**
